name: Flutter iOS Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get

      - name: Setup iOS Configuration
        run: |
          rm -rf ios
          flutter create . --platforms=ios
          cd ios
          # Crea un Podfile corretto includendo il riferimento agli script di Flutter
          cat <<EOF > Podfile
          platform :ios, '15.0'
          
          # Carica gli script di Flutter necessari per CocoaPods
          flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          
          target 'Runner' do
            use_frameworks!
            use_modular_headers!
          end
          EOF

      - name: Build IPA
        run: |
          # Forza il target 15.0 nel progetto Xcode
          sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g" ios/Runner.xcodeproj/project.pbxproj
          
          # Compilazione
          flutter build ios --release --no-codesign
          
          # Creazione IPA
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: app.ipa
